[target.aarch64-linux-android]
ar = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"
linker = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android26-clang.cmd"

[target.armv7-linux-androideabi]
ar = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"
linker = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi26-clang.cmd"

[target.x86_64-linux-android]
ar = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"
linker = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\x86_64-linux-android26-clang.cmd"

[env]
ANDROID_NDK_HOME = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638"
CC_aarch64_linux_android = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android26-clang.cmd"
CC_armv7_linux_androideabi = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi26-clang.cmd"
CC_x86_64_linux_android = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\x86_64-linux-android26-clang.cmd"
CXX_aarch64_linux_android = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android26-clang++.cmd"
CXX_armv7_linux_androideabi = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi26-clang++.cmd"
CXX_x86_64_linux_android = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\x86_64-linux-android26-clang++.cmd"
AR_aarch64_linux_android = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"
AR_armv7_linux_androideabi = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"
AR_x86_64_linux_android = "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\ndk\\30.0.15729638\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"