$ErrorActionPreference="Stop"
Set-StrictMode -Version 2.0
$RepoRoot=Split-Path -Parent $PSScriptRoot;Set-Location -LiteralPath $RepoRoot
$ExpectedSource="e13579b";$ExpectedNative="81384E504737D9531ABC6C81D70F3225B2D30574C23E00587EBD5772779AD790";$ExpectedBinding="8C0BB329466B44ECDE6F5DFFD8212EC7CBF69C1BC0696AFB752BE87551AD9304";$Jdk="C:\Program Files\Android\Android Studio\jbr"
$Prefix=Join-Path $env:TEMP "apu-file-exchange-keystore-build";$State="$Prefix-state.json";$Log="$Prefix-gradle.log";$Existing=@(@($State,$Log)|Where-Object{Test-Path $_});if($Existing.Count){throw "File exchange store build already attempted"}
$Head=((& git rev-parse HEAD)-join"").Trim();& git diff --quiet $ExpectedSource $Head -- android-app rust-core;if($LASTEXITCODE -ne 0){throw "Source mismatch"}
$Native="android-app/app/src/main/jniLibs/arm64-v8a/libp2p_core.so";$Binding="android-app/app/src/main/java/uniffi/p2p_core/p2p_core.kt";$Status=@(& git status --porcelain=v1 --untracked-files=all);if($Status.Count -ne 1 -or $Status[0] -ne " M $Native"){throw "Unexpected worktree"};if((Get-FileHash $Native -Algorithm SHA256).Hash -ne $ExpectedNative -or (Get-FileHash $Binding -Algorithm SHA256).Hash -ne $ExpectedBinding){throw "Artifact mismatch"}
$Outcome="INCOMPLETE_DO_NOT_REPEAT";$Failure=$null;$ApkHash=$null;$ApkSize=$null;$TestHash=$null;$TestSize=$null
try{$env:JAVA_HOME=$Jdk;$env:Path="$Jdk\bin;"+$env:Path;$env:GITHUB_REF_NAME="v11.16.48";Push-Location "android-app";try{$Old=$ErrorActionPreference;$ErrorActionPreference="Continue";& .\gradlew.bat --no-daemon :app:assembleDebug :app:assembleDebugAndroidTest *>&1|Tee-Object $Log|Out-Host;$Code=$LASTEXITCODE;$ErrorActionPreference=$Old;if($Code -ne 0){throw "Gradle failed: $Code"}}finally{Pop-Location};$Apk="android-app/app/build/outputs/apk/debug/app-debug.apk";$Test="android-app/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk";$ApkSize=(Get-Item $Apk).Length;$ApkHash=(Get-FileHash $Apk -Algorithm SHA256).Hash;$TestSize=(Get-Item $Test).Length;$TestHash=(Get-FileHash $Test -Algorithm SHA256).Hash;$Outcome="PASS"}catch{$Failure=$_.Exception.Message;throw}finally{[ordered]@{schema=1;purpose="Device-bound file exchange identity store build";outcome=$Outcome;failure=$Failure;sourceCommit=$ExpectedSource;appApkSize=$ApkSize;appApkSha256=$ApkHash;testApkSize=$TestSize;testApkSha256=$TestHash;phonesChanged=$false;adbUsed=$false}|ConvertTo-Json -Depth 5|Set-Content $State -Encoding UTF8;$Hash=(Get-FileHash $State -Algorithm SHA256).Hash;Write-Host "`nOutcome: $Outcome";Write-Host "State: $State";Write-Host "State SHA256: $Hash";Write-Host "App APK: $ApkSize / $ApkHash";Write-Host "Test APK: $TestSize / $TestHash";Write-Host "ADB/phones: False/False"};if($Outcome -ne "PASS"){throw "File exchange store build failed"};Write-Host "FILE EXCHANGE KEYSTORE BUILD PASS"
