$ErrorActionPreference="Stop"
Set-StrictMode -Version 2.0
$RepoRoot=Split-Path -Parent $PSScriptRoot;Set-Location $RepoRoot
$Adb="C:\Users\User\AppData\Local\Android\Sdk\platform-tools\adb.exe";$Package="com.vladimir.messenger";$Apk=Join-Path $RepoRoot "android-app\app\build\outputs\apk\debug\app-debug.apk"
$ExpectedApk="E89935E83EA02C047357DC03532D73A01B69D5E880C227947A15C64019113ADC";$BuildState=Join-Path $env:TEMP "apu-m8-device-marker-migration-build-state.json";$ExpectedBuildState="32AA6AED65D3C22B02A2B0766938F9BA1776B00E5EB12DF84BD86C4DADC90FA9";$StatePath=Join-Path $env:TEMP "apu-m8-device-marker-migration-phone-state.json"
if(Test-Path $StatePath){throw "Marker migration phone gate already attempted; preserve evidence"};if((Get-FileHash $BuildState -Algorithm SHA256).Hash -ne $ExpectedBuildState){throw "Build evidence mismatch"};if((Get-FileHash $Apk -Algorithm SHA256).Hash -ne $ExpectedApk){throw "APK mismatch"}
$Phones=@([pscustomobject]@{Name="Anna";Serial="AUYF6R5923006121";Before="v11.16.20";Expected="preserved"},[pscustomobject]@{Name="Zhenya";Serial="3B665800EES00000";Before="v11.16.20";Expected="discarded"},[pscustomobject]@{Name="Stas";Serial="11567254BK001192";Before="v11.16.19";Expected="preserved"})
$Visible=@{};foreach($Line in @(& $Adb devices)){if($Line -match "^(\S+)\s+(\S+)$"){$Visible[$Matches[1]]=$Matches[2]}};foreach($Phone in $Phones){if(-not $Visible.ContainsKey($Phone.Serial) -or $Visible[$Phone.Serial] -ne "device"){throw "$($Phone.Name) unavailable"}}
$Result=[ordered]@{schema=1;outcome="INCOMPLETE_DO_NOT_REPEAT";purpose="differential marker migration: preserve usable local keys, discard restored unusable key";startedUtc=(Get-Date).ToUniversalTime().ToString("o");apkSha256=$ExpectedApk;phones=@();uninstallUsed=$false;dataClearCommandUsed=$false;installReplaceUsed=$true;logcatCleared=$false};$Result|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8
try{foreach($Phone in $Phones){$Serial=$Phone.Serial;$BeforeDump=@(& $Adb -s $Serial shell dumpsys package $Package);$BeforeVersion=((($BeforeDump|Where-Object{$_ -match "^\s*versionName="}|Select-Object -First 1) -as [string]).Trim()-replace"versionName=","");if($BeforeVersion -ne $Phone.Before){throw "$($Phone.Name) pre-version mismatch: $BeforeVersion"};$Install=((& $Adb -s $Serial install -r $Apk)-join" ").Trim();if($LASTEXITCODE -ne 0 -or $Install -notmatch "Success"){throw "$($Phone.Name) replace install failed"};$Launch=((& $Adb -s $Serial shell am start -W -n "$Package/.MainActivity")-join" ").Trim();Start-Sleep 8;$PidText=((& $Adb -s $Serial shell pidof $Package)-join" ").Trim();if(-not $PidText){throw "$($Phone.Name) launch failed"};$Prefs=@(& $Adb -s $Serial shell run-as $Package ls shared_prefs 2>$null);$Files=@(& $Adb -s $Serial shell run-as $Package ls files 2>$null);$Markers=@(& $Adb -s $Serial shell run-as $Package ls no_backup 2>$null);$Profile=@($Prefs|Where-Object{$_ -match "p2p_prefs\.xml"}).Count;$Relay=@($Files|Where-Object{$_ -match "apu_relay\.sqlite"}).Count;$Marker=@($Markers|Where-Object{$_ -match "apu_identity_device_v1"}).Count;$Log=@(& $Adb -s $Serial logcat --pid=$PidText -d -t 1200);$Text=$Log -join"`n";$Migrated=$Text -match "Created device marker for existing usable local identity";$Discarded=$Text -match "Discarded restored identity/chat/custody state without device marker";if($Phone.Expected -eq "preserved"){if($Profile -ne 1 -or $Marker -ne 1 -or -not $Migrated){throw "$($Phone.Name) legitimate migration failed: profile=$Profile marker=$Marker migrated=$Migrated"}}else{if($Profile -ne 0 -or $Relay -ne 0 -or $Marker -ne 0 -or -not $Discarded){throw "$($Phone.Name) restored-state discard failed: profile=$Profile relay=$Relay marker=$Marker discarded=$Discarded"}};$Dump=@(& $Adb -s $Serial shell dumpsys package $Package);$Version=(($Dump|Where-Object{$_ -match "^\s*versionName="}|Select-Object -First 1) -as [string]).Trim();if($Version -ne "versionName=v11.16.22"){throw "$($Phone.Name) post-version mismatch"};$Entry=[pscustomobject]@{Name=$Phone.Name;Serial=$Serial;beforeVersion=$BeforeVersion;expected=$Phone.Expected;install=$Install;version=$Version;processId=$PidText;profilePrefs=$Profile;relayFiles=$Relay;deviceMarkers=$Marker;migrationLog=$Migrated;discardLog=$Discarded;launch=$Launch};$Result.phones+=@($Entry);$Result|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8;Write-Host "$($Phone.Name): v11.16.22 expected=$($Phone.Expected) profile=$Profile relay=$Relay marker=$Marker"};$Result.outcome="PASS";$Result.completedUtc=(Get-Date).ToUniversalTime().ToString("o")}finally{$Result|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8}
$Hash=(Get-FileHash $StatePath -Algorithm SHA256).Hash;Write-Host "`nOutcome: $($Result.outcome)";Write-Host "State: $StatePath";Write-Host "State SHA256: $Hash";Write-Host "Migration checks: $($Result.phones.Count)/3";Write-Host "M8 DEVICE MARKER MIGRATION PHONE PASS"
