$ErrorActionPreference="Stop"
Set-StrictMode -Version 2.0
$RepoRoot=Split-Path -Parent $PSScriptRoot;Set-Location $RepoRoot
$Adb="C:\Users\User\AppData\Local\Android\Sdk\platform-tools\adb.exe";$Package="com.vladimir.messenger";$Apk=Join-Path $RepoRoot "android-app\app\build\outputs\apk\debug\app-debug.apk"
$ExpectedApk="8FA37AB34FD4B9C6D1A8F6C0BD6E3E3C8E253FE936C7CE94B2B9FABE2FFC3E3A";$ExpectedSo="08E5153EDAE051700B31F0DFF7525927FE2D8070C635406E07C76F98128710C4";$BuildState=Join-Path $env:TEMP "apu-m8-backup-policy-build-state.json";$ExpectedBuildState="5D886A5C314515B6F4C8545019C128AEFE67E8667BD36FC69D34E61160754E08"
$StatePath=Join-Path $env:TEMP "apu-m8-no-restore-clean-install-state.json";if(Test-Path $StatePath){throw "No-restore clean install already attempted; preserve evidence"}
$Phones=@([pscustomobject]@{Name="Anna";Serial="AUYF6R5923006121"},[pscustomobject]@{Name="Zhenya";Serial="3B665800EES00000"},[pscustomobject]@{Name="Stas";Serial="11567254BK001192"})
if((Get-FileHash $BuildState -Algorithm SHA256).Hash -ne $ExpectedBuildState){throw "Build state mismatch"};if((Get-FileHash $Apk -Algorithm SHA256).Hash -ne $ExpectedApk){throw "APK mismatch"};$So=Join-Path $RepoRoot "android-app\app\src\main\jniLibs\arm64-v8a\libp2p_core.so";if((Get-FileHash $So -Algorithm SHA256).Hash -ne $ExpectedSo){throw "Native mismatch"}
$Visible=@{};foreach($Line in @(& $Adb devices)){if($Line -match "^(\S+)\s+(\S+)$"){$Visible[$Matches[1]]=$Matches[2]}};foreach($Phone in $Phones){if(-not $Visible.ContainsKey($Phone.Serial) -or $Visible[$Phone.Serial] -ne "device"){throw "$($Phone.Name) unavailable"}}
$Result=[ordered]@{schema=1;outcome="INCOMPLETE_DO_NOT_REPEAT";purpose="prove clean install does not restore stale identity/chat state";startedUtc=(Get-Date).ToUniversalTime().ToString("o");version="v11.16.20";apkSha256=$ExpectedApk;phones=@();uninstallUsed=$true;dataAndCacheDeleted=$true;forceStopUsed=$false;logcatCleared=$false};$Result|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8
try{foreach($Phone in $Phones){$Serial=$Phone.Serial;$Uninstall=((& $Adb -s $Serial uninstall $Package)-join" ").Trim();if($LASTEXITCODE -ne 0 -or $Uninstall -notmatch "Success"){throw "$($Phone.Name) uninstall failed"};$Install=((& $Adb -s $Serial install $Apk)-join" ").Trim();if($LASTEXITCODE -ne 0 -or $Install -notmatch "Success"){throw "$($Phone.Name) install failed"};$Launch=((& $Adb -s $Serial shell am start -W -n "$Package/.MainActivity")-join" ").Trim();Start-Sleep 6;$PidText=((& $Adb -s $Serial shell pidof $Package)-join" ").Trim();if(-not $PidText){throw "$($Phone.Name) launch failed"};$Prefs=@(& $Adb -s $Serial shell run-as $Package ls shared_prefs 2>$null);$Files=@(& $Adb -s $Serial shell run-as $Package ls files 2>$null);$Profile=@($Prefs|Where-Object{$_ -match "p2p_prefs\.xml"});$Relay=@($Files|Where-Object{$_ -match "apu_relay\.sqlite"});$Wrong=@($Files|Where-Object{$_ -match "apu_relay\.sqlite\.relay\.sqlite"});if($Profile.Count -ne 0 -or $Relay.Count -ne 0 -or $Wrong.Count -ne 0){throw "$($Phone.Name) stale state restored: profile=$($Profile.Count) relay=$($Relay.Count) wrong=$($Wrong.Count)"};$Dump=@(& $Adb -s $Serial shell dumpsys package $Package);$Version=(($Dump|Where-Object{$_ -match "^\s*versionName="}|Select-Object -First 1) -as [string]).Trim();if($Version -ne "versionName=v11.16.20"){throw "$($Phone.Name) version mismatch"};$Entry=[pscustomobject]@{Name=$Phone.Name;Serial=$Serial;uninstall=$Uninstall;install=$Install;version=$Version;processId=$PidText;profilePrefsBeforeOnboarding=$Profile.Count;relayFilesBeforeOnboarding=$Relay.Count;wrongSuffixFiles=$Wrong.Count;launch=$Launch};$Result.phones+=@($Entry);$Result|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8;Write-Host "$($Phone.Name): v11.16.20 clean, no restored profile/relay, PID=$PidText"};$Result.outcome="PASS";$Result.completedUtc=(Get-Date).ToUniversalTime().ToString("o")}finally{$Result|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8}
$Hash=(Get-FileHash $StatePath -Algorithm SHA256).Hash;Write-Host "`nOutcome: $($Result.outcome)";Write-Host "State: $StatePath";Write-Host "State SHA256: $Hash";Write-Host "Phones no-restore: $($Result.phones.Count)/3";Write-Host "M8 NO-RESTORE CLEAN INSTALL PASS"
