$ErrorActionPreference="Stop"
Set-StrictMode -Version 2.0
$Adb="C:\Users\User\AppData\Local\Android\Sdk\platform-tools\adb.exe";$Package="com.vladimir.messenger";$PriorAnna=Join-Path $env:TEMP "apu-m8-v111622-sigkill-recovery-logs\Anna.log";$StatePath=Join-Path $env:TEMP "apu-m8-v111622-process-recovery-resume.json";$LogRoot=Join-Path $env:TEMP "apu-m8-v111622-process-recovery-resume-logs"
if((Test-Path $StatePath) -or (Test-Path $LogRoot)){throw "Process recovery resume already attempted; preserve evidence"};if(-not(Test-Path $PriorAnna)){throw "Prior Anna PASS log missing"}
function Test-Log([string]$Path){$Text=(Get-Content $Path)-join"`n";return [pscustomobject]@{Engine=$Text -match "Engine started\. NodeId:";Durable=$Text -match "Relay custody mode: durable-encrypted, quarantined: 0";Exact=$Text -match "encrypted relay store opened at .*apu_relay\.sqlite";Wrong=$Text -match "apu_relay\.sqlite\.relay\.sqlite";Fatal=$Text -match "FATAL EXCEPTION"}}
$AnnaCheck=Test-Log $PriorAnna;if(-not $AnnaCheck.Engine -or -not $AnnaCheck.Durable -or -not $AnnaCheck.Exact -or $AnnaCheck.Wrong -or $AnnaCheck.Fatal){throw "Prior Anna evidence no longer proves PASS"};New-Item -ItemType Directory -Path $LogRoot|Out-Null
$Results=@([pscustomobject]@{Name="Anna";Serial="AUYF6R5923006121";Method="prior SIGKILL PASS";LogPath=$PriorAnna;LogSha256=(Get-FileHash $PriorAnna -Algorithm SHA256).Hash;Engine=$true;Durable=$true;Exact=$true;Wrong=$false;Fatal=$false})
$Phones=@([pscustomobject]@{Name="Zhenya";Serial="3B665800EES00000"},[pscustomobject]@{Name="Stas";Serial="11567254BK001192"})
foreach($Phone in $Phones){$Serial=$Phone.Serial;$Before=((& $Adb -s $Serial shell pidof $Package)-join" ").Trim();if($Before){& $Adb -s $Serial shell run-as $Package kill -9 $Before;Start-Sleep 3;$Survivor=((& $Adb -s $Serial shell pidof $Package)-join" ").Trim();if($Survivor -eq $Before){throw "$($Phone.Name) PID survived"};$Method="SIGKILL"}else{$Method="cold start from not-running"};$Current=((& $Adb -s $Serial shell pidof $Package)-join" ").Trim();if(-not $Current){$Launch=((& $Adb -s $Serial shell am start -W -n "$Package/.MainActivity")-join" ").Trim();if($LASTEXITCODE -ne 0){throw "$($Phone.Name) launch failed"}};Start-Sleep 15;$NewPid=((& $Adb -s $Serial shell pidof $Package)-join" ").Trim();if(-not $NewPid){throw "$($Phone.Name) did not recover"};$Log=@(& $Adb -s $Serial logcat --pid=$NewPid -d -t 2500);$Path=Join-Path $LogRoot "$($Phone.Name).log";$Log|Set-Content $Path -Encoding UTF8;$Check=Test-Log $Path;$Files=@(& $Adb -s $Serial shell run-as $Package ls files 2>$null);$ExactCount=@($Files|Where-Object{$_ -match "^apu_relay\.sqlite(?:-wal|-shm)?$"}).Count;$WrongCount=@($Files|Where-Object{$_ -match "^apu_relay\.sqlite\.relay\.sqlite"}).Count;Write-Host "$($Phone.Name): method=$Method before=$Before after=$NewPid engine=$($Check.Engine) durable0=$($Check.Durable) exact=$($Check.Exact)/$ExactCount wrong=$($Check.Wrong)/$WrongCount fatal=$($Check.Fatal)";if(-not $Check.Engine -or -not $Check.Durable -or -not $Check.Exact -or $ExactCount -ne 3 -or $Check.Wrong -or $WrongCount -or $Check.Fatal){throw "$($Phone.Name) recovery failed; preserve $Path"};$Results+=[pscustomobject]@{Name=$Phone.Name;Serial=$Serial;Method=$Method;BeforePid=$Before;AfterPid=$NewPid;LogPath=$Path;LogSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;Engine=$Check.Engine;Durable=$Check.Durable;Exact=$Check.Exact;ExactFiles=$ExactCount;Wrong=$Check.Wrong;WrongFiles=$WrongCount;Fatal=$Check.Fatal}}
$State=[ordered]@{schema=1;outcome="PASS";completedUtc=(Get-Date).ToUniversalTime().ToString("o");phones=$Results;forceStopUsed=$false;dataCleared=$false;cacheCleared=$false;logcatCleared=$false};$State|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8;$Hash=(Get-FileHash $StatePath -Algorithm SHA256).Hash;Write-Host "`nOutcome: PASS";Write-Host "State: $StatePath";Write-Host "State SHA256: $Hash";Write-Host "Durable/quarantine0/exact: 3/3";Write-Host "M8 PROCESS RECOVERY RESUME PASS"
