$ErrorActionPreference="Stop"
Set-StrictMode -Version 2.0

# Clean v11.16.19 install after exact relay DB path build PASS.
$RepoRoot=Split-Path -Parent $PSScriptRoot;Set-Location $RepoRoot
$Adb="C:\Users\User\AppData\Local\Android\Sdk\platform-tools\adb.exe";$Sdk="C:\Users\User\AppData\Local\Android\Sdk";$Jdk="C:\Program Files\Android\Android Studio\jbr";$Package="com.vladimir.messenger"
$Apk=Join-Path $RepoRoot "android-app\app\build\outputs\apk\debug\app-debug.apk";$ExpectedApkHash="811E2D3F8D7C22C5D72F60650B380FC7B1DF5B828BD63C877F91B0BAEC48BF02";$ExpectedSoHash="08E5153EDAE051700B31F0DFF7525927FE2D8070C635406E07C76F98128710C4";$ExpectedSigner="40448024EB6A824709431EB8908176F5D08BE8EAD1A8902EEB5F0FDAA1B3A186";$BuildState=Join-Path $env:TEMP "apu-m8-relay-path-fix-state.json";$ExpectedBuildStateHash="A6DDD4ED4175C56B864CA9A1A778A4D3B8D96CB55D30D21BAA09D9038450D5F6"
$StatePath=Join-Path $env:TEMP "apu-m8-relay-path-fix-clean-install-state.json";if(Test-Path $StatePath){throw "v11.16.19 clean install already attempted; preserve evidence"}
$Phones=@([pscustomobject]@{Name="Anna";Serial="AUYF6R5923006121"},[pscustomobject]@{Name="Zhenya";Serial="3B665800EES00000"},[pscustomobject]@{Name="Stas";Serial="11567254BK001192"})
if((Get-FileHash $BuildState -Algorithm SHA256).Hash -ne $ExpectedBuildStateHash){throw "Build evidence mismatch"};if((Get-FileHash $Apk -Algorithm SHA256).Hash -ne $ExpectedApkHash){throw "APK mismatch"};$So=Join-Path $RepoRoot "android-app\app\src\main\jniLibs\arm64-v8a\libp2p_core.so";if((Get-FileHash $So -Algorithm SHA256).Hash -ne $ExpectedSoHash){throw "Native mismatch"}
$ExpectedStatus=" M android-app/app/src/main/jniLibs/arm64-v8a/libp2p_core.so";$Status=@(& git status --porcelain=v1 --untracked-files=all);if($Status.Count -ne 1 -or $Status[0] -ne $ExpectedStatus){throw "Unexpected worktree"}
$Visible=@{};foreach($Line in @(& $Adb devices)){if($Line -match "^(\S+)\s+(\S+)$"){$Visible[$Matches[1]]=$Matches[2]}};foreach($Phone in $Phones){if(-not $Visible.ContainsKey($Phone.Serial) -or $Visible[$Phone.Serial] -ne "device"){throw "$($Phone.Name) unavailable"}}
$env:JAVA_HOME=$Jdk;$env:Path="$Jdk\bin;"+$env:Path;$Tools=Get-ChildItem (Join-Path $Sdk "build-tools") -Directory|Sort-Object Name -Descending|Where-Object{Test-Path (Join-Path $_.FullName "apksigner.bat")}|Select-Object -First 1;$SignerTool=Join-Path $Tools.FullName "apksigner.bat"
function Get-Signer([string]$Path){$Old=$ErrorActionPreference;$ErrorActionPreference="Continue";$Out=@(& $SignerTool verify --print-certs $Path 2>&1|ForEach-Object{$_.ToString()});$Code=$LASTEXITCODE;$ErrorActionPreference=$Old;if($Code -ne 0){throw "Signer check failed"};$Line=$Out|Where-Object{$_ -match "certificate SHA-256 digest:"}|Select-Object -First 1;$Value=(($Line -split "digest:",2)[1] -replace":","");$Value=$Value.Trim();return $Value.ToUpperInvariant()}
if((Get-Signer $Apk) -ne $ExpectedSigner){throw "Target signer mismatch"}
$Result=[ordered]@{schema=1;outcome="INCOMPLETE_DO_NOT_REPEAT";authorizedCleanInstall=$true;startedUtc=(Get-Date).ToUniversalTime().ToString("o");version="v11.16.19";apkSha256=$ExpectedApkHash;nativeSha256=$ExpectedSoHash;phones=@();dataAndCacheDeleted=$true;forceStopUsed=$false;logcatCleared=$false};$Result|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8
try{foreach($Phone in $Phones){$Serial=$Phone.Serial;$Before=@(& $Adb -s $Serial shell dumpsys package $Package);$BeforeVersion=(($Before|Where-Object{$_ -match "^\s*versionName="}|Select-Object -First 1) -as [string]).Trim();if($BeforeVersion -ne "versionName=v11.16.18"){throw "$($Phone.Name) pre-version mismatch: $BeforeVersion"};$Uninstall=((& $Adb -s $Serial uninstall $Package)-join" ").Trim();if($LASTEXITCODE -ne 0 -or $Uninstall -notmatch "Success"){throw "$($Phone.Name) uninstall failed"};$Install=((& $Adb -s $Serial install $Apk)-join" ").Trim();if($LASTEXITCODE -ne 0 -or $Install -notmatch "Success"){throw "$($Phone.Name) install failed"};$Dump=@(& $Adb -s $Serial shell dumpsys package $Package);$Version=(($Dump|Where-Object{$_ -match "^\s*versionName="}|Select-Object -First 1) -as [string]).Trim();if($Version -ne "versionName=v11.16.19"){throw "$($Phone.Name) post-version mismatch"};$Launch=((& $Adb -s $Serial shell am start -W -n "$Package/.MainActivity")-join" ").Trim();Start-Sleep 4;$PidText=((& $Adb -s $Serial shell pidof $Package)-join" ").Trim();if(-not $PidText){throw "$($Phone.Name) launch failed"};$Entry=[pscustomobject]@{Name=$Phone.Name;Serial=$Serial;beforeVersion=$BeforeVersion;uninstall=$Uninstall;install=$Install;version=$Version;launch=$Launch;processId=$PidText};$Result.phones+=@($Entry);$Result|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8;Write-Host "$($Phone.Name): clean v11.16.19 PID=$PidText"};$Result.outcome="PASS";$Result.completedUtc=(Get-Date).ToUniversalTime().ToString("o")}finally{$Result|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8}
$Hash=(Get-FileHash $StatePath -Algorithm SHA256).Hash;Write-Host "`nOutcome: $($Result.outcome)";Write-Host "State: $StatePath";Write-Host "State SHA256: $Hash";Write-Host "Phones: $($Result.phones.Count)/3";Write-Host "Data/cache deleted: True";Write-Host "M8 RELAY PATH FIX CLEAN INSTALL PASS"
