$ErrorActionPreference="Stop"
Set-StrictMode -Version 2.0
$Adb="C:\Users\User\AppData\Local\Android\Sdk\platform-tools\adb.exe";$Package="com.vladimir.messenger";$StatePath=Join-Path $env:TEMP "apu-m8-v111622-final-readiness.json";$LogRoot=Join-Path $env:TEMP "apu-m8-v111622-final-readiness-logs"
if((Test-Path $StatePath) -or (Test-Path $LogRoot)){throw "Final readiness already attempted; preserve evidence"}
$Phones=@([pscustomobject]@{Name="Anna";Serial="AUYF6R5923006121"},[pscustomobject]@{Name="Zhenya";Serial="3B665800EES00000"},[pscustomobject]@{Name="Stas";Serial="11567254BK001192"})
$Visible=@{};foreach($Line in @(& $Adb devices)){if($Line -match "^(\S+)\s+(\S+)$"){$Visible[$Matches[1]]=$Matches[2]}};foreach($Phone in $Phones){if(-not $Visible.ContainsKey($Phone.Serial) -or $Visible[$Phone.Serial] -ne "device"){throw "$($Phone.Name) unavailable"}}
New-Item -ItemType Directory -Path $LogRoot|Out-Null;$Results=@();Write-Host "=== V11.16.22 FINAL READINESS (READ-ONLY) ==="
foreach($Phone in $Phones){$Serial=$Phone.Serial;$Dump=@(& $Adb -s $Serial shell dumpsys package $Package);$Version=(($Dump|Where-Object{$_ -match "^\s*versionName="}|Select-Object -First 1) -as [string]).Trim();if($Version -ne "versionName=v11.16.22"){throw "$($Phone.Name) version mismatch: $Version"};$PidText=((& $Adb -s $Serial shell pidof $Package)-join" ").Trim();if(-not $PidText){throw "$($Phone.Name) process missing"};$PrefsText=(& $Adb -s $Serial exec-out run-as $Package cat shared_prefs/p2p_prefs.xml 2>$null)-join"`n";$Identity=$PrefsText -match '<boolean\s+name="identity_created"\s+value="true"\s*/>';$Prefs=@(& $Adb -s $Serial shell run-as $Package ls shared_prefs 2>$null);$Files=@(& $Adb -s $Serial shell run-as $Package ls files 2>$null);$Markers=@(& $Adb -s $Serial shell run-as $Package ls no_backup 2>$null);$Marker=@($Markers|Where-Object{$_ -match "^apu_identity_device_v1$"}).Count -eq 1;$KeyPrefs=@($Prefs|Where-Object{$_ -match "^apu_relay_at_rest\.xml$"}).Count;$Exact=@($Files|Where-Object{$_ -match "^apu_relay\.sqlite(?:-wal|-shm)?$"}).Count;$Wrong=@($Files|Where-Object{$_ -match "^apu_relay\.sqlite\.relay\.sqlite"}).Count;$Log=@(& $Adb -s $Serial logcat --pid=$PidText -d -t 2500);$LogPath=Join-Path $LogRoot "$($Phone.Name).log";$Log|Set-Content $LogPath -Encoding UTF8;$Text=$Log -join"`n";$Durable=$Text -match "Relay custody mode: durable-encrypted, quarantined: 0";$Fatal=$Text -match "FATAL EXCEPTION";$Jobs=((& $Adb -s $Serial shell dumpsys jobscheduler $Package)-join"`n");$Work=$Jobs -match "SystemJobService|com\.vladimir\.messenger";Write-Host "$($Phone.Name): PID=$PidText identity=$Identity marker=$Marker keyPrefs=$KeyPrefs exact=$Exact wrong=$Wrong durable0=$Durable work=$Work fatal=$Fatal";if(-not $Identity -or -not $Marker -or $KeyPrefs -ne 1 -or $Exact -ne 3 -or $Wrong -ne 0 -or -not $Durable -or -not $Work -or $Fatal){throw "$($Phone.Name) readiness failed; preserve $LogPath"};$Results+=[pscustomobject]@{Name=$Phone.Name;Serial=$Serial;Version=$Version;ProcessId=$PidText;IdentityCreated=$Identity;DeviceMarker=$Marker;KeyPrefs=$KeyPrefs;ExactRelayFiles=$Exact;WrongRelayFiles=$Wrong;DurableEncryptedQuarantineZero=$Durable;WorkManagerVisible=$Work;Fatal=$Fatal;LogPath=$LogPath;LogSha256=(Get-FileHash $LogPath -Algorithm SHA256).Hash}}
$State=[ordered]@{schema=1;outcome="PASS";capturedUtc=(Get-Date).ToUniversalTime().ToString("o");phones=$Results;phoneChanges=$false;installPerformed=$false;forceStopUsed=$false;logcatCleared=$false;dataCleared=$false};$State|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8;$Hash=(Get-FileHash $StatePath -Algorithm SHA256).Hash;Write-Host "`nOutcome: PASS";Write-Host "State: $StatePath";Write-Host "State SHA256: $Hash";Write-Host "Ready durable/quarantine0/work: 3/3";Write-Host "Phone changes: False";Write-Host "M8 V11.16.22 FINAL READINESS PASS"
