$ErrorActionPreference="Stop"
Set-StrictMode -Version 2.0

# Read-only continuation after v3 proved Anna's installed signer differs.
$RepoRoot=Split-Path -Parent $PSScriptRoot;Set-Location $RepoRoot
$Sdk="C:\Users\User\AppData\Local\Android\Sdk";$Jdk="C:\Program Files\Android\Android Studio\jbr";$Adb=Join-Path $Sdk "platform-tools\adb.exe";$Apk=Join-Path $RepoRoot "android-app\app\build\outputs\apk\release\app-release.apk";$Package="com.vladimir.messenger"
$ExpectedApkHash="246ED1355F77013D8BA47AFF9D860514E137F7072CBF639AC4131FF376FFCE44";$ExpectedTargetSigner="F843CBE70332BAB67A9671EBDE32FEE541E84CD904D3A508E5626346A1A4A5F7"
$StatePath=Join-Path $env:TEMP "apu-m8e-phone-signer-inventory-v4.json";$CaptureRoot=Join-Path $env:TEMP "apu-m8e-installed-apk-signatures-v4"
if((Test-Path -LiteralPath $StatePath)-or(Test-Path -LiteralPath $CaptureRoot)){throw "Signer inventory v4 already attempted; preserve evidence"}
$Phones=@([pscustomobject]@{Name="Anna";Serial="AUYF6R5923006121"},[pscustomobject]@{Name="Zhenya";Serial="3B665800EES00000"},[pscustomobject]@{Name="Stas";Serial="11567254BK001192"})
$env:JAVA_HOME=$Jdk;$env:Path="$Jdk\bin;"+$env:Path
$BuildTools=Get-ChildItem -LiteralPath (Join-Path $Sdk "build-tools") -Directory|Sort-Object Name -Descending|Where-Object{Test-Path -LiteralPath (Join-Path $_.FullName "apksigner.bat")}|Select-Object -First 1
if(-not $BuildTools){throw "apksigner missing"};$ApkSigner=Join-Path $BuildTools.FullName "apksigner.bat"
function Get-Signer([string]$Path){$Old=$ErrorActionPreference;$ErrorActionPreference="Continue";$Output=@(& $ApkSigner verify --print-certs $Path 2>&1|ForEach-Object{$_.ToString()});$Code=$LASTEXITCODE;$ErrorActionPreference=$Old;if($Code -ne 0){throw "apksigner failed: $Path exit=$Code"};$Line=$Output|Where-Object{$_ -match "certificate SHA-256 digest:"}|Select-Object -First 1;if(-not $Line){throw "Signer missing: $Path"};$Digest=(($Line -split "digest:",2)[1] -replace ":","");$Digest=$Digest.Trim();return $Digest.ToUpperInvariant()}

Write-Host "=== M8-E INSTALLED SIGNER INVENTORY V4 (READ-ONLY) ==="
if((Get-FileHash $Apk -Algorithm SHA256).Hash -ne $ExpectedApkHash){throw "Target APK changed"};$TargetSigner=Get-Signer $Apk;if($TargetSigner -ne $ExpectedTargetSigner){throw "Target signer changed"}
$Lines=@(& $Adb devices);$Visible=@{};foreach($Line in $Lines){if($Line -match "^(\S+)\s+(\S+)$"){$Visible[$Matches[1]]=$Matches[2]}};foreach($Phone in $Phones){if(-not $Visible.ContainsKey($Phone.Serial) -or $Visible[$Phone.Serial] -ne "device"){throw "$($Phone.Name) not ready"}}
New-Item -ItemType Directory -Path $CaptureRoot|Out-Null;$Results=@()
foreach($Phone in $Phones){$Serial=$Phone.Serial;$Paths=@(& $Adb -s $Serial shell pm path $Package|ForEach-Object{$_.Trim()});$Base=$Paths|Where-Object{$_ -match "^package:.*base\.apk$"}|Select-Object -First 1;if(-not $Base){$Base=$Paths|Where-Object{$_ -match "^package:"}|Select-Object -First 1};if(-not $Base){throw "$($Phone.Name) package missing"};$Remote=$Base -replace"^package:","";$Local=Join-Path $CaptureRoot "$($Phone.Name)-installed-base.apk";& $Adb -s $Serial pull $Remote $Local|Out-Host;if($LASTEXITCODE -ne 0){throw "$($Phone.Name) pull failed"};$Signer=Get-Signer $Local;$Hash=(Get-FileHash $Local -Algorithm SHA256).Hash;$Dump=@(& $Adb -s $Serial shell dumpsys package $Package);$Version=(($Dump|Where-Object{$_ -match "^\s*versionName="}|Select-Object -First 1) -as [string]).Trim();$Code=(($Dump|Where-Object{$_ -match "^\s*versionCode="}|Select-Object -First 1) -as [string]).Trim();$First=(($Dump|Where-Object{$_ -match "^\s*firstInstallTime="}|Select-Object -First 1) -as [string]).Trim();$Updated=(($Dump|Where-Object{$_ -match "^\s*lastUpdateTime="}|Select-Object -First 1) -as [string]).Trim();$Uid=(($Dump|Where-Object{$_ -match "^\s*(userId|appId)="}|Select-Object -First 1) -as [string]).Trim();$Compatible=$Signer -eq $TargetSigner;Write-Host "$($Phone.Name): $Version; $Code; signer=$Signer; compatible=$Compatible";$Results+=[pscustomobject]@{Name=$Phone.Name;Serial=$Serial;VersionName=$Version;VersionCode=$Code;FirstInstallTime=$First;LastUpdateTime=$Updated;Uid=$Uid;InstalledApkSha256=$Hash;InstalledSignerSha256=$Signer;TargetUpgradeCompatible=$Compatible}}
$Groups=@($Results|Group-Object InstalledSignerSha256|ForEach-Object{[pscustomobject]@{Signer=$_.Name;Phones=@($_.Group.Name);Count=$_.Count}});$AllCompatible=@($Results|Where-Object{-not $_.TargetUpgradeCompatible}).Count -eq 0
$State=[ordered]@{schema=4;outcome="PASS";capturedUtc=(Get-Date).ToUniversalTime().ToString("o");targetApkSha256=$ExpectedApkHash;targetSignerSha256=$TargetSigner;phones=$Results;signerGroups=$Groups;allPhonesUpgradeCompatible=$AllCompatible;installPerformed=$false;appLaunched=$false;forceStopUsed=$false;logcatCleared=$false;dataCleared=$false}
$State|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $StatePath -Encoding UTF8;$StateHash=(Get-FileHash $StatePath -Algorithm SHA256).Hash
Write-Host "`nState: $StatePath";Write-Host "State SHA256: $StateHash";Write-Host "Signer groups: $($Groups.Count)";Write-Host "All compatible with target: $AllCompatible";Write-Host "Phone changes: False";Write-Host "M8-E INSTALLED SIGNER INVENTORY V4 PASS"
