org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true

# ВАЖНО: configuration-cache ЛОМАЕТ UniFFI и копирование .so — отключаем
org.gradle.configuration-cache=false

# AndroidX (обязательно для Compose)
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

org.gradle.caching=false